### ISSUE TITLE
Something wrong with test code

### ISSUE THREAD

**Issue by 5663015** [Jongchan/tensorflow-vdsr#10]
![image](https://cloud.githubusercontent.com/assets/8531141/23576865/75ca9ba4-00eb-11e7-86a3-ca7c99e6dcb3.png)
Traceback (most recent call last):
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _do_call
    return fn(*args)
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 1003, in _run_fn
    status, run_metadata)
  File "D:\python351\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\python351\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file .\checkpoints\VDSR_adam_epoch_000.ckpt-3364.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_31 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_31/tensor_names, save/RestoreV2_31/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Machine_Learning/Tensorflow_Code/example_code/tensorflow-vdsr-master/TEST.py", line 94, in <module>
    test_VDSR_with_sess(80, model_ckpt, DATA_PATH,sess)
  File "E:/Machine_Learning/Tensorflow_Code/example_code/tensorflow-vdsr-master/TEST.py", line 50, in test_VDSR_with_sess
    saver.restore(sess, ckpt_path)
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "D:\python351\lib\site-packages\tensorflow\python\client\session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file .\checkpoints\VDSR_adam_epoch_000.ckpt-3364.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_31 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_31/tensor_names, save/RestoreV2_31/shape_and_slices)]]

Caused by op 'save/RestoreV2_31', defined at:
  File "E:/Machine_Learning/Tensorflow_Code/example_code/tensorflow-vdsr-master/TEST.py", line 86, in <module>
    saver = tf.train.Saver(weights)
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 1000, in __init__
    self.build()
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 624, in build
    restore_sequentially, reshape)
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "D:\python351\lib\site-packages\tensorflow\python\training\saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "D:\python351\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "D:\python351\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "D:\python351\lib\site-packages\tensorflow\python\framework\ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\python351\lib\site-packages\tensorflow\python\framework\ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file .\checkpoints\VDSR_adam_epoch_000.ckpt-3364.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/RestoreV2_31 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_31/tensor_names, save/RestoreV2_31/shape_and_slices)]]

I have run train code ,but I just run here "[epoch 1.0101] loss 1.3370	 lr 0.00001" . This process cost me 20 hours with cpu , I have to stop it.
Sorry to copy too much information  .  I am a new learner on SR and TensorFlow , maybe some simple problem occurred but I can't find it . How can I fix this problem ? Thanks your answer very much ~

**Comment by Jongchan** [comment]
1) have you tried the checkpoint file I provided? I don't recognize the checkpoint format you used. I guess this may come from TF version difference. I am using TF 0.8 version.
2) If you are going to do deep learning, I strongly recommend you to use a GPU with 6GB or more memory. It only takes several hours to train VDSR with GPU (I use GTX1080).
