### ISSUE TITLE
Error in testing 

### ISSUE THREAD

**Issue by Lakshya-Kejriwal** [Jongchan/tensorflow-vdsr#8]
I am trying to replicate the results on test Set5 and Set14. I downloaded the checkpoint file given and the test sets and also ran aug_test.m. But on running TEST.py I am getting the following error:

`Traceback (most recent call last):
 File "TEST.py", line 88, in <module>
    test_VDSR_with_sess(80, model_ckpt, DATA_PATH,sess)
  File "TEST.py", line 49, in test_VDSR_with_sess
    saver.restore(sess, ckpt_path)
  File "/home/lakshya/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/lakshya/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/lakshya/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/lakshya/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/lakshya/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "shared_model/conv_00_w" not found in checkpoint files ./checkpoints/VDSR_norm_0.01_epoch_066.ckpt-16820
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
	 [[Node: save/RestoreV2_8/_61 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_183_save/RestoreV2_8", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`

How can I replicate the results?

**Comment by Jongchan** [comment]
Some of the codes got mixed up. Sorry for the confusion.
Remove the 
```
shared_model = tf.make_template('shared_model', model) 
output_tensor, weights = shared_model(input_tensor
```

and change it into

```
output_tensor, weights = model(input_tensor)
```
